# Generated by Django 2.1.5 on 2019-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300, verbose_name='text')),
            ],
            options={
                'verbose_name': 'reviews',
            },
        ),
    ]
