# Generated by Django 2.1.5 on 2019-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsmodel',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Отзыв'),
        ),
    ]
